export const words = [
  { id: 1, idCourse: 3, name: "mi", meanings: ["je", "moi, nous"] },
  { id: 2, idCourse: 3, name: "sina", meanings: ["tu", "toi", "vous"] },
  { id: 3, idCourse: 3, name: "ona", meanings: ["il.s", "elle.s", "eux"] },
  { id: 4, idCourse: 3, name: "jan", meanings: ["être humain", "personne", "quelqu'un"] },
  { id: 5, idCourse: 3, name: "ijo", meanings: ["chose", "quelque chose", "phénomène", "objet", "matière", "machin", "un être"] },
  { id: 6, idCourse: 3, name: "suli", meanings: ["grand", "lourd", "gros", "long", "important", "adulte"] },
  { id: 7, idCourse: 3, name: "lili", meanings: ["petit", "un peu", "jeune"] },
  { id: 8, idCourse: 3, name: "moku", meanings: ["nourriture", "manger", "boire", "consommer", "avaler"] },
  { id: 9, idCourse: 3, name: "li", meanings: ["p. (sépare le sujet du prédicat)"] },
  { id: 10, idCourse: 4, name: "soweli", meanings: ["animal", "mammifère terrestre"] },
  { id: 11, idCourse: 4, name: "akesi", meanings: ["animal non-mignon", "reptile", "batracien", "amphibien"] },
  { id: 12, idCourse: 4, name: "pipi", meanings: ["insecte", "araignée", "fourmi"] },
  { id: 13, idCourse: 4, name: "waso", meanings: ["oiseau", "créature volante", "animal ailé"] },
  { id: 14, idCourse: 4, name: "kala", meanings: ["poisson", "animal marin"] },
  { id: 15, idCourse: 4, name: "kasi", meanings: ["plante", "végétation", "herbe", "feuille"] },
  { id: 16, idCourse: 4, name: "kili", meanings: ["fruit", "légume", "champignon"] },
  { id: 17, idCourse: 4, name: "wawa", meanings: ["énergie", "puissance", "fort", "puissant", "sûr", "fiable", "confiant", "énergique", "intense"] },
  { id: 18, idCourse: 4, name: "mu", meanings: ["p. (cri d'animal, communication animale)"] },
  { id: 19, idCourse: 5, name: "kulupu", meanings: ["groupe", "communauté", "société, nation", "tribu", "compagnie"] },
  { id: 20, idCourse: 5, name: "mama", meanings: ["parent", "père", "mère", "ancêtre", "créateur", "celui ou celle qui prend soin"] },
  { id: 21, idCourse: 5, name: "meli", meanings: ["femme", "épouse", "petite amie", "femelle", "féminin"] },
  { id: 22, idCourse: 5, name: "mije", meanings: ["homme", "mari", "petit ami", "mâle", "masculin"] },
  { id: 23, idCourse: 5, name: "tonsi", meanings: ["non-binaire", "non-conforme aux normes de genre", "transgenre"] },
  { id: 24, idCourse: 5, name: "olin", meanings: ["amour", "affection", "aimer", "respecter", "compatir", "montrer de l'affection pour"] },
  { id: 25, idCourse: 5, name: "toki", meanings: ["langage", "communiquer", "dire", "parler", "penser"] },
  { id: 26, idCourse: 5, name: "ma", meanings: ["terre", "sol", "monde", "pays", "région", "territoire", "lieu en plein air"] },
  { id: 27, idCourse: 5, name: "tomo", meanings: ["construction", "habitation", "espace intérieur", "lieu couvert", "maison", "bâtiment", "édifice", "pièce", "chambre", "demeure", "chez soi"] },
  { id: 28, idCourse: 6, name: "pona", meanings: ["réparer", "bon", "positif", "utile", "paisible", "simple", "sympa"] },
  { id: 29, idCourse: 6, name: "ike", meanings: ["mal", "mauvais", "négatif", "compliqué", "superflu", "non pertinent"] },
  { id: 30, idCourse: 6, name: "poki", meanings: ["sac", "verre", "coupe", "boîte", "bol", "récipient", "tasse", "placard", "tiroir", "vase"] },
  { id: 31, idCourse: 6, name: "pakala", meanings: ["accident", "détruire", "brisé", "cassé", "abîmé", "bâclé", "gâché"] },
  { id: 32, idCourse: 6, name: "utala", meanings: ["guerre", "bataille", "combattre", "se battre contre", "lutter contre"] },
  { id: 33, idCourse: 6, name: "palisa", meanings: ["objet long dur et/ou pointu", "bâton"] },
  { id: 34, idCourse: 6, name: "mute", meanings: ["quantité", "beaucoup de", "plusieurs", "plus de", "nombreux", "très"] },
  { id: 35, idCourse: 6, name: "ni", meanings: ["ce", "cette", "ces", "ceci", "cela"] },
  { id: 36, idCourse: 7, name: "telo", meanings: ["eau", "liquide", "fluide", "substance mouillée", "boisson"] },
  { id: 37, idCourse: 7, name: "seli", meanings: ["feu", "chaleur", "élément de cuisson", "réaction chimique", "chaud"] },
  { id: 38, idCourse: 7, name: "kiwen", meanings: ["objet dur", "métal", "pierre", "caillou", "dur comme la pierre"] },
  { id: 39, idCourse: 7, name: "lawa", meanings: ["tête", "dominer", "diriger", "guider", "mener", "posséder", "régler", "principal"] },
  { id: 40, idCourse: 7, name: "sitelen", meanings: ["image", "représentation", "symbole", "marque", "écriture", "dessiner", "écrire"] },
  { id: 41, idCourse: 7, name: "pali", meanings: ["acte", "activité", "travail", "faire", "fabriquer", "travailler", "construire", "préparer", "agir sur"] },
  { id: 42, idCourse: 7, name: "kute", meanings: ["oreille", "entendre", "écouter", "obéir", "faire attention à"] },
  { id: 43, idCourse: 7, name: "e", meanings: ["p. (introduit le complément d'objet direct)"] },
  { id: 44, idCourse: 8, name: "ala", meanings: ["aucun", "zéro", "rien", "non", "ne", "pas"] },
  { id: 45, idCourse: 8, name: "ali", meanings: ["tout", "abondance", "la vie", "l'univers", "tous", "abondants", "innombrables", "nombre 100"] },
  { id: 46, idCourse: 8, name: "kon", meanings: ["air", "atmosphère", "vent", "souffle", "essence", "esprit", "réalité caché", "agent invisible"] },
  { id: 47, idCourse: 8, name: "lipu", meanings: ["objet plat", "feuille", "page", "livre", "document", "carte", "papier", "site web"] },
  { id: 48, idCourse: 8, name: "jo", meanings: ["possession", "avoir", "contenir", "porter", "tenir"] },
  { id: 49, idCourse: 8, name: "alasa", meanings: ["chasser", "cueillir", "fouiller", "chercher", "essayer", "tenter"] },
  { id: 50, idCourse: 8, name: "lukin", meanings: ["vision", "regard", "regarder", "voir", "examiner", "observer", "lire", "surveiller", "chercher à", "essayer de"] },
  { id: 51, idCourse: 8, name: "taso", meanings: ["mais", "cependant", "seulement"] },
  { id: 52, idCourse: 10, name: "oko", meanings: ["oeil"] },
  { id: 53, idCourse: 10, name: "uta", meanings: ["bouche", "lèvres", "cavité buccale", "mâchoire"] },
  { id: 54, idCourse: 10, name: "nena", meanings: ["bosse", "montagne", "colline", "nez", "bouton"] },
  { id: 55, idCourse: 10, name: "lupa", meanings: ["porte", "trou", "orifice", "fenêtre"] },
  { id: 56, idCourse: 10, name: "sinpin", meanings: ["mur", "face", "front", "visage", "poitrine", "avant", "devant"] },
  { id: 57, idCourse: 10, name: "linja", meanings: ["objet long et flexible", "corde", "cheveu", "fil", "ligne"] },
  { id: 58, idCourse: 10, name: "luka", meanings: ["bras", "main", "organe du toucher", "cinq"] },
  { id: 59, idCourse: 10, name: "en", meanings: ["et"] },
  { id: 60, idCourse: 10, name: "anu", meanings: ["ou"] },
  { id: 61, idCourse: 11, name: "pilin", meanings: ["coeur (physique et psychologique)", "sentir", "penser", "qui ressent"] },
  { id: 62, idCourse: 11, name: "sijelo", meanings: ["corps", "état physique", "torse"] },
  { id: 63, idCourse: 11, name: "monsi", meanings: ["fesses", "dos", "derrière", "arrière"] },
  { id: 64, idCourse: 11, name: "insa", meanings: ["centre", "contenu", "intérieur", "estomac", "viscères", "dedans", "entre"] },
  { id: 65, idCourse: 11, name: "poka", meanings: ["côté", "proximité", "hanche", "proche", "à côté", "auprès", "en compagnie de"] },
  { id: 66, idCourse: 11, name: "noka", meanings: ["partie inférieure", "organe de locomotion", "pied", "jambe", "bas", "dessous"] },
  { id: 67, idCourse: 11, name: "selo", meanings: ["forme", "couche extérieure", "écorce", "pelure", "coquille", "limite", "surface externe", "peau"] },
  { id: 68, idCourse: 11, name: "ko", meanings: ["argile", "pâte", "poudre", "substance collante", "semi-solide"] },
  { id: 69, idCourse: 11, name: "pi", meanings: ["p. (\"de\")"] },
  { id: 70, idCourse: 12, name: "lape", meanings: ["repos", "dormir", "dormant", "se reposant"] },
  { id: 71, idCourse: 12, name: "unpa", meanings: ["sexe", "sexuel", "avoir des rapports sexuels avec"] },
  { id: 72, idCourse: 12, name: "kama", meanings: ["futur", "qui arrive", "qui vient", "venir", "advenir", "devenir", "arriver à", "réussir à", "être la cause de", "venu"] },
  { id: 73, idCourse: 12, name: "wile", meanings: ["désir", "devoir", "vouloir", "avoir besoin de"] },
  { id: 74, idCourse: 12, name: "awen", meanings: ["attendre", "rester", "demeurer", "continuer à", "resté", "protégé", "gardé", "conservé", "qui attend", "qui persiste"] },
  { id: 75, idCourse: 12, name: "sona", meanings: ["connaissance", "sagesse", "savoir", "connaître"] },
  { id: 76, idCourse: 12, name: "ken", meanings: ["possibilité", "pouvoir", "possible", "être capable de"] },
  { id: 77, idCourse: 13, name: "ilo", meanings: ["outil", "machine", "instrument", "équipement", "appareil"] },
  { id: 78, idCourse: 13, name: "jaki", meanings: ["ordure", "dégoûtant", "obscène", "maladif", "toxique", "impur", "insalubre", "sale"] },
  { id: 79, idCourse: 13, name: "lon", meanings: ["exister", "présent", "réel", "vrai", "actuel", "à/sur/en/dans", "situé à/sur/en/dans"] },
  { id: 80, idCourse: 13, name: "tawa", meanings: ["aller voir", "déplacer", "se déplacer", "en mouvement", "animé", "à", "allant à", "vers", "pour", "du point de vue de", "selon"] },
  { id: 81, idCourse: 13, name: "tan", meanings: ["origine", "cause", "provenance", "provenant de", "parce que", "à cause de", "de"] },
  { id: 82, idCourse: 13, name: "sama", meanings: ["semblable", "fraternel", "homologue", "identique", "similaire", "l'un l'autre", "même", "comme"] },
  { id: 83, idCourse: 13, name: "kepeken", meanings: ["utiliser", "en utilisant", "au moyen de"] },
  { id: 84, idCourse: 14, name: "pana", meanings: ["donner", "envoyer", "mettre", "fournir", "émettre", "lâcher", "libérer"] },
  { id: 85, idCourse: 14, name: "musi", meanings: ["jeu", "divertissement", "amuser", "jouer", "artistique", "frivole", "divertissant", "amusant"] },
  { id: 86, idCourse: 14, name: "open", meanings: ["commencer", "ouvrir", "allumer", "démarrer"] },
  { id: 87, idCourse: 14, name: "pini", meanings: ["fin", "finir", "arrêter", "éteindre", "fini", "passé", "terminé"] },
  { id: 88, idCourse: 14, name: "anpa", meanings: ["sol", "bas", "baisser", "vaincre", "incliné vers le bas", "humble", "qui dépend", "profond", "prosterné"] },
  { id: 89, idCourse: 14, name: "sewi", meanings: ["haut", "ciel", "toit", "chose élevée", "partie supérieure", "divin", "sacré", "surnaturel", "supérieur", "inspirant le respect/crainte", "dessus"] },
  { id: 90, idCourse: 14, name: "tenpo", meanings: ["temps", "durée", "moment", "occasion", "période", "situation"] },
  { id: 91, idCourse: 15, name: "mani", meanings: ["argent", "monnaie", "richesse", "grand animal domestiqué"] },
  { id: 92, idCourse: 15, name: "nasa", meanings: ["fou", "bête", "idiot", "étrange", "bizarre", "insolite", "stupide", "ivre"] },
  { id: 93, idCourse: 15, name: "len", meanings: ["tissu", "vêtement", "textile", "couverture", "rideau d'intimité", "vêtir"] },
  { id: 94, idCourse: 15, name: "suwi", meanings: ["sucré", "doux", "parfumé", "mignon", "innocent", "adorable"] },
  { id: 95, idCourse: 15, name: "weka", meanings: ["retirer", "éliminer", "absent", "enlevé", "éloigné", "au loin"] },
  { id: 96, idCourse: 15, name: "moli", meanings: ["mort", "mourir", "tuer", "mourant"] },
  { id: 97, idCourse: 15, name: "seme", meanings: ["p. (pronom interrogatif)", "quoi?", "quel?"] },
  { id: 98, idCourse: 16, name: "kule", meanings: ["couleur", "colorer", "coloré", "pigmenté", "peint"] },
  { id: 99, idCourse: 16, name: "pimeja", meanings: ["noir", "foncé", "sombre"] },
  { id: 100, idCourse: 16, name: "walo", meanings: ["blanc", "clair", "pâle"] },
  { id: 101, idCourse: 16, name: "loje", meanings: ["rouge"] },
  { id: 102, idCourse: 16, name: "laso", meanings: ["bleu", "vert"] },
  { id: 103, idCourse: 16, name: "jelo", meanings: ["jaune"] },
  { id: 104, idCourse: 17, name: "lete", meanings: ["froid", "frais", "cru"] },
  { id: 105, idCourse: 17, name: "kalama", meanings: ["son", "bruit", "émettre un son", "réciter", "proférer"] },
  { id: 106, idCourse: 17, name: "nimi", meanings: ["mot", "nom"] },
  { id: 107, idCourse: 17, name: "supa", meanings: ["meuble", "surface", "surface horizontale sur laquelle on pose quelque chose"] },
  { id: 108, idCourse: 17, name: "kin", meanings: ["vraiment", "certes", "également"] },
  { id: 109, idCourse: 17, name: "a", meanings: ["p. (accent, émotion, confirmation)", "ah", "oh", "heu", "hein"] },
  { id: 110, idCourse: 17, name: "o", meanings: ["p. (introduit le vocatif et l'impératif)", "hé", "ô"] },
  { id: 111, idCourse: 18, name: "nanpa", meanings: ["nombre", "-ième"] },
  { id: 112, idCourse: 18, name: "wan", meanings: ["un", "unité", "unique", "uni"] },
  { id: 113, idCourse: 18, name: "tu", meanings: ["deux", "diviser", "séparer", "fendre"] },
  { id: 114, idCourse: 18, name: "esun", meanings: ["marché", "boutique", "foire", "magasin", "commerce"] },
  { id: 115, idCourse: 18, name: "pan", meanings: ["pain", "céréale", "pâtes", "riz", "blé", "orge", "maïs", "avoine"] },
  { id: 116, idCourse: 18, name: "sike", meanings: ["objet rond", "ballon", "boule", "cercle", "cycle", "sphère", "roue", "anneau", "annuel"] },
  { id: 117, idCourse: 18, name: "ante", meanings: ["autre", "différent", "changé"] },
  { id: 118, idCourse: 19, name: "suno", meanings: ["soleil", "lumière", "lueur", "brillant"] },
  { id: 119, idCourse: 19, name: "mun", meanings: ["lune", "astre", "étoile"] },
  { id: 120, idCourse: 19, name: "sin", meanings: ["nouveau", "frais", "encore", "encore un", "de plus", "en plus"] },
  { id: 121, idCourse: 19, name: "nasin", meanings: ["chemin", "voie", "manière", "façon", "coutume", "méthode", "doctrine", "rue"] },
  { id: 122, idCourse: 19, name: "pu", meanings: ["interaction avec le livre officiel du toki pona"] },
  { id: 123, idCourse: 19, name: "la", meanings: ["p. (contexte)"] },
]
