export const words = [
  { id: 1, name: "mi", meanings: ["je", "moi", "nous"] },
  { id: 2, name: "sina", meanings: ["tu", "toi", "vous"] },
  { id: 3, name: "ona", meanings: ["il.s", "elle.s", "eux"] },
  { id: 4, name: "jan", meanings: ["être humain", "personne", "quelqu'un"] },
  { id: 5, name: "ijo", meanings: ["chose", "quelque chose", "phénomène", "objet", "matière", "machin", "un être"] },
  { id: 6, name: "suli", meanings: ["grand", "lourd", "gros", "long", "important", "adulte"] },
  { id: 7, name: "lili", meanings: ["petit", "un peu", "jeune"] },
  { id: 8, name: "moku", meanings: ["nourriture", "manger", "boire", "consommer", "avaler"] },
  { id: 9, name: "li", meanings: ["p. (sépare le sujet du prédicat)"] },
  { id: 99, name: "a", meanings: ["p. (accent, émotion, confirmation), ah, oh, heu, hein"] },
  { id: 99, name: "akesi", meanings: ["animal non-mignon, reptile, batracien, amphibien"] },
  { id: 99, name: "ala", meanings: ["aucun, zéro, rien, non, ne, pas"] },
  { id: 99, name: "alasa", meanings: ["chasser, cueillir, fouiller, chercher, essayer, tenter"] },
  { id: 99, name: "ali", meanings: ["tout, abondance, la vie, l'univers, tous, abondants, innombrables, nombre 100"] },
  { id: 99, name: "anpa", meanings: ["sol, bas, baisser, vaincre, incliné vers le bas, humble, qui dépend, profond, prosterné"] },
  { id: 99, name: "ante", meanings: ["autre, différent, changé"] },
  { id: 99, name: "anu", meanings: ["ou"] },
  { id: 99, name: "awen", meanings: ["attendre, rester, demeurer, continuer à, resté, protégé, gardé, conservé, qui attend, qui persiste"] },
  { id: 99, name: "e", meanings: ["p. (introduit le complément d'objet direct)"] },
  { id: 99, name: "en", meanings: ["et"] },
  { id: 99, name: "esun", meanings: ["marché, boutique, foire, magasin, commerce"] },
  { id: 99, name: "ike", meanings: ["mal, mauvais, négatif, compliqué, superflu, non pertinent"] },
  { id: 99, name: "ilo", meanings: ["outil, machine, instrument, équipement, appareil"] },
  { id: 99, name: "insa", meanings: ["centre, contenu, intérieur, estomac, viscères, dedans, entre"] },
  { id: 99, name: "jaki", meanings: ["ordure, dégoûtant, obscène, maladif, toxique, impur, insalubre, sale"] },
  { id: 99, name: "jelo", meanings: ["jaune"] },
  { id: 99, name: "jo", meanings: ["possession, avoir, contenir, porter, tenir"] },
  { id: 99, name: "kala", meanings: ["poisson, animal marin"] },
  { id: 99, name: "kalama", meanings: ["son, bruit, émettre un son, réciter, proférer"] },
  { id: 99, name: "kama", meanings: ["futur, qui arrive, qui vient, venir, advenir, devenir, arriver à, réussir à, être la cause de, venu"] },
  { id: 99, name: "kasi", meanings: ["plante, végétation, herbe, feuille"] },
  { id: 99, name: "ken", meanings: ["possibilité, pouvoir, possible, être capable de"] },
  { id: 99, name: "kepeken", meanings: ["utiliser, en utilisant, au moyen de"] },
  { id: 99, name: "kili", meanings: ["fruit, légume, champignon"] },
  { id: 99, name: "kin", meanings: ["vraiment, certes, également"] },
  { id: 99, name: "kiwen", meanings: ["objet dur, métal, pierre, caillou, dur comme la pierre"] },
  { id: 99, name: "ko", meanings: ["argile, pâte, poudre, substance collante, semi-solide"] },
  { id: 99, name: "kon", meanings: ["air, atmosphère, vent, souffle, essence, esprit, réalité caché, agent invisible"] },
  { id: 99, name: "kule", meanings: ["couleur, colorer, coloré, pigmenté, peint"] },
  { id: 99, name: "kulupu", meanings: ["groupe, communauté, société, nation, tribu, compagnie"] },
  { id: 99, name: "kute", meanings: ["oreille, entendre, écouter, obéir, faire attention à"] },
  { id: 99, name: "la", meanings: ["p. (contexte)"] },
  { id: 99, name: "lape", meanings: ["repos, dormir, dormant, se reposant"] },
  { id: 99, name: "laso", meanings: ["bleu, vert"] },
  { id: 99, name: "lawa", meanings: ["tête, dominer, diriger, guider, mener, posséder, régler, principal"] },
  { id: 99, name: "len", meanings: ["tissu, vêtement, textile, couverture, rideau d'intimité, vêtir"] },
  { id: 99, name: "lete", meanings: ["froid, frais, cru"] },
  { id: 99, name: "linja", meanings: ["objet long et flexible, corde, cheveu, fil, ligne"] },
  { id: 99, name: "lipu", meanings: ["objet plat, feuille, page, livre, document, carte, papier, site web"] },
  { id: 99, name: "loje", meanings: ["rouge"] },
  { id: 99, name: "lon", meanings: ["exister, présent, réel, vrai, actuel, à/sur/en/dans, situé à/sur/en/dans"] },
  { id: 99, name: "luka", meanings: ["bras, main, organe du toucher, cinq"] },
  { id: 99, name: "lukin", meanings: ["vision, regard, regarder, voir, examiner, observer, lire, surveiller, chercher à, essayer de"] },
  { id: 99, name: "lupa", meanings: ["porte, trou, orifice, fenêtre"] },
  { id: 99, name: "ma", meanings: ["terre, sol, monde, pays, région, territoire, lieu en plein air"] },
  { id: 99, name: "mama", meanings: ["parent, père, mère, ancêtre, créateur, celui ou celle qui prend soin"] },
  { id: 99, name: "mani", meanings: ["argent, monnaie, richesse, grand animal domestiqué"] },
  { id: 99, name: "meli", meanings: ["femme, épouse, petite amie, femelle, féminin"] },
  { id: 99, name: "mije", meanings: ["homme, mari, petit ami, mâle, masculin"] },
  { id: 99, name: "moli", meanings: ["mort, mourir, tuer, mourant"] },
  { id: 99, name: "monsi", meanings: ["fesses, dos, derrière, arrière"] },
  { id: 99, name: "mu", meanings: ["p. (cri d'animal, communication animale), miaou, meuh, ouah"] },
  { id: 99, name: "mun", meanings: ["lune, astre, étoile"] },
  { id: 99, name: "musi", meanings: ["jeu, divertissement, amuser, jouer, artistique, frivole, divertissant, amusant"] },
  { id: 99, name: "mute", meanings: ["quantité, beaucoup de, plusieurs, plus de, nombreux, très"] },
  { id: 99, name: "nanpa", meanings: ["nombre, -ième"] },
  { id: 99, name: "nasa", meanings: ["fou, bête, idiot, étrange, bizarre, insolite, stupide, ivre"] },
  { id: 99, name: "nasin", meanings: ["chemin, voie, manière, façon, coutume, méthode, doctrine, rue"] },
  { id: 99, name: "nena", meanings: ["bosse, montagne, colline, nez, bouton"] },
  { id: 99, name: "ni", meanings: ["ce, cette, ces, ceci, cela"] },
  { id: 99, name: "nimi", meanings: ["mot, nom"] },
  { id: 99, name: "noka", meanings: ["partie inférieure, organe de locomotion, pied, jambe, bas, dessous"] },
  { id: 99, name: "o", meanings: ["p. (introduit le vocatif et l'impératif), hé, ô"] },
  { id: 99, name: "oko", meanings: ["oeil"] },
  { id: 99, name: "olin", meanings: ["amour, affection, aimer, respecter, compatir, montrer de l'affection pour"] },
  { id: 99, name: "open", meanings: ["commencer, ouvrir, allumer, démarrer"] },
  { id: 99, name: "pakala", meanings: ["accident, détruire, brisé, cassé, abîmé, bâclé, gâché"] },
  { id: 99, name: "pali", meanings: ["acte, activité, travail, faire, fabriquer, travailler, construire, préparer, agir sur"] },
  { id: 99, name: "palisa", meanings: ["objet long dur et/ou pointu, bâton"] },
  { id: 99, name: "pan", meanings: ["pain, céréale, pâtes, riz, blé, orge, maïs, avoine"] },
  { id: 99, name: "pana", meanings: ["donner, envoyer, mettre, fournir, émettre, lâcher, libérer"] },
  { id: 99, name: "pi", meanings: ["p. (\"de\")"] },
  { id: 99, name: "pilin", meanings: ["coeur (physique et psychologique), sentir, penser, qui ressent"] },
  { id: 99, name: "pimeja", meanings: ["noir, foncé, sombre"] },
  { id: 99, name: "pini", meanings: ["fin, finir, arrêter, éteindre, fini, passé, terminé"] },
  { id: 99, name: "pipi", meanings: ["insecte, araignée, fourmi"] },
  { id: 99, name: "poka", meanings: ["côté, proximité, hanche, proche, à côté, auprès, en compagnie de"] },
  { id: 99, name: "poki", meanings: ["sac, verre, coupe, boîte, bol, récipient, tasse, placard, tiroir, vase"] },
  { id: 99, name: "pona", meanings: ["réparer, bon, positif, utile, paisible, simple, sympa"] },
  { id: 99, name: "pu", meanings: ["interaction avec le livre officiel toki pona"] },
  { id: 99, name: "sama", meanings: ["semblable, fraternel, homologue, identique, similaire, l'un l'autre, même, comme"] },
  { id: 99, name: "seli", meanings: ["feu, chaleur, élément de cuisson, réaction chimique, chaud"] },
  { id: 99, name: "selo", meanings: ["forme, couche extérieure, écorce, pelure, coquille, limite, surface externe, peau"] },
  { id: 99, name: "seme", meanings: ["p. (pronom interrogatif) quoi?, quel?"] },
  { id: 99, name: "sewi", meanings: ["haut, ciel, toit, chose élevée, partie supérieure, divin, sacré, surnaturel, supérieur, inspirant le respect/crainte, dessus"] },
  { id: 99, name: "sijelo", meanings: ["corps, état physique, torse"] },
  { id: 99, name: "sike", meanings: ["objet rond, ballon, boule, cercle, cycle, sphère, roue, anneau, annuel"] },
  { id: 99, name: "sin", meanings: ["nouveau, frais, encore, encore un, de plus, en plus"] },
  { id: 99, name: "sinpin", meanings: ["mur, face, front, visage, poitrine, avant, devant"] },
  { id: 99, name: "sitelen", meanings: ["image, représentation, symbole, marque, écriture, dessiner, écrire"] },
  { id: 99, name: "sona", meanings: ["connaissance, sagesse, savoir, connaître"] },
  { id: 99, name: "soweli", meanings: ["animal, mammifère terrestre"] },
  { id: 99, name: "suno", meanings: ["soleil, lumière, lueur, brillant"] },
  { id: 99, name: "supa", meanings: ["meuble, surface, surface horizontale servant d'étagère"] },
  { id: 99, name: "suwi", meanings: ["sucré, doux, parfumé, mignon, innocent, adorable"] },
  { id: 99, name: "tan", meanings: ["origine, cause, provenance, provenant de, parce que, à cause de, de"] },
  { id: 99, name: "taso", meanings: ["mais, cependant, seulement"] },
  { id: 99, name: "tawa", meanings: ["aller voir, déplacer, se déplacer, en mouvement, animé, à, allant à, vers, pour, du point de vue de, selon"] },
  { id: 99, name: "telo", meanings: ["eau, liquide, fluide, substance mouillée, boisson"] },
  { id: 99, name: "tenpo", meanings: ["temps, durée, moment, occassion, période, situation"] },
  { id: 99, name: "toki", meanings: ["langage, communiquer, dire, parler, penser"] },
  { id: 99, name: "tomo", meanings: ["construction, habitation, espace intérieur, lieu couvert, maison, bâtiment, édifice, pièce, chambre, demeure, chez soi"] },
  { id: 99, name: "tu", meanings: ["deux, diviser, séparer, fendre"] },
  { id: 99, name: "unpa", meanings: ["sexe, sexuel, avoir des rapports sexuels avec"] },
  { id: 99, name: "uta", meanings: ["bouche, lèvres, cavité bucale, mâchoire"] },
  { id: 99, name: "utala", meanings: ["guerre, bataille, combattre, se battre contre, lutter contre"] },
  { id: 99, name: "walo", meanings: ["blanc, clair, pâle"] },
  { id: 99, name: "wan", meanings: ["un, unité, unique, uni"] },
  { id: 99, name: "waso", meanings: ["oiseau, créature volante, animal ailé"] },
  { id: 99, name: "wawa", meanings: ["énergie, puissance, fort, puissant, sûr, fiable, confiant, énergique, intense"] },
  { id: 99, name: "weka", meanings: ["retirer, éliminer, absent, enlevé, éloigné, au loin"] },
  { id: 99, name: "wile", meanings: ["désir, devoir, vouloir, avoir besoin de"] },
];